version: '3.9'

services:
  service-backend:
    restart: on-failure
    container_name: "api-hmdressrecommender-alpermulayim"
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: "jdbc:mysql://mysqldb:3306/db_hm_dress_recommender?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false" 
    depends_on:
      - mysqldb

  mysqldb:
    stdin_open: true
    container_name: "db-hmdressrecommender-alpermulayim"
    image: mysql
    ports: 
      - "3306:3306"
    volumes:
      - ./db/:/data/db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=db_hm_dress_recommender
      - MYSQL_PASSWORD=rootpass

