CREATE TABLE IF NOT EXISTS hm_product_attributes (
	id INTEGER NOT NULL,
    product_id INTEGER,
    color VARCHAR(40),
    material VARCHAR(80),
    style VARCHAR(90),
    season VARCHAR(80),
    CONSTRAINT PRIMARY KEY(id)
);

INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 1, 1, "red","jean","summer","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 2, 2, "brown","linen","summer","formal");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 3, 3, "brown","cotton","summer","sport");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 4, 4, "pink","cotton","summer","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 5, 5, "gray","linen","spring","sport");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 6, 6, "blue","denim","winter","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 7, 7, "black","cotton","spring","sport");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 8, 8, "white","polyester","summer","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 9, 9, "blue","denim","winter","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 10, 10, "black","denim","summer","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 11, 11, "blue","cotton","summer","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 12, 12, "brown","silk","summer","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 13, 13, "white","cotton","summer","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 14, 14, "black","polyester","summer","sport");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 15, 15, "black","wool","winter","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 16, 16, "brown","polyester","winter","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 17, 17, "brown","blue","summer","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 18, 18, "black","cotton","summer","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 19, 19, "pink","wool","winter","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 20, 20, "black","silk","spring","formal");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 21, 21, "brown","polyester","winter","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 22, 22, "white","polyester","winter","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 23, 23, "gray","cotton","winter","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 24, 24, "blue","cotton","winter","formal");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 25, 25, "white","cotton","summer","formal");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 26, 26, "brown","denim","winter","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 27, 27, "brown","polyester","spring","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 28, 28, "black","cotton","winter","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 29, 29, "gray","polyester","winter","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 30, 30, "blue","wool","winter","formal");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 31, 31, "black","cotton","winter","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 32, 32, "brown","cotton","summer","sport");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 33, 33, "white","cotton","spring","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 34, 34, "blue","cotton","summer","sport");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 35, 35, "yellow","cotton","summer","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 36, 36, "brown","cotton","summer","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 37, 37, "gray","cotton","spring","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 38, 38, "black","cotton","winter","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 39, 39, "brown","cotton","summer","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 40, 40, "pink","cotton","summer","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 41, 41, "gray","cotton","summer","sport");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 42, 42, "black","cotton","summer","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 43, 43, "white","wool","winter","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 44, 44, "pink","cotton","winter","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 45, 45, "brown","cotton","summer","sport");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 46, 46, "black","cotton","winter","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 47, 47, "pink","cotton","spring","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 48, 48, "yellow","cotton","summer","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 49, 49, "gray","cotton","spring","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 50, 50, "blue","cotton","summer","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 51, 51, "navy blue","canvas","spring","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 52, 52, "gray","leather","summer","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 53, 53, "red","Synthetic Leather","spring","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 54, 54, "black","canvas","spring","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 55, 55, "blue","Synthetic Leather","summer","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 56, 56, "brown","suede","winter","formal");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 57, 57, "black","leather","spring","formal");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 58, 58, "yellow","Synthetic Leather","summer","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 59, 59, "green","suede","winter","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 60, 60, "brown","leather","summer","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 61, 61, "black","canvas","spring","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 62, 62, "gray","leather","summer","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 63, 63, "blue","suede","winter","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 64, 64, "green","Synthetic Leather","summer","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 65, 65, "navy blue","canvas","spring","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 66, 66, "black","suede","winter","formal");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 67, 67, "yellow","Leather","spring","formal");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 68, 68, "brown","Synthetic Leather","summer","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 69, 69, "blue","suede","winter","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 70, 70, "white","canvas","winter","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 71, 71, "black","canvas","spring","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 72, 72, "black","Synthetic Leather","summer","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 73, 73, "yellow","canvas","summer","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 74, 74, "navy blue","suede","spring","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 75, 75, "black","canvas","spring","sport");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 76, 76, "white","leather","winter","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 77, 77, "green","canvas","spring","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 78, 78, "gray","mesh","spring","sport");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 79, 79, "brown","leather","summer","sport");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 80, 80, "black","leather","summer","sport");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 81, 81, "brown","leather","winter","formal");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 82, 82, "red","wool","winter","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 83, 83, "black","fabric","winter","formal");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 84, 84, "gray","leather","spring","formal");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 85, 85, "white","wool","winter","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 86, 86, "brown","leather","winter","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 87, 87, "black","Synthetic Leather","winter","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 88, 88, "brown","leather","summer","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 89, 89, "white","wool","winter","casual");
INSERT INTO  hm_product_attributes (id, product_id, color, material, season, style) VALUES( 90, 90, "red","fabric","winter","formal");
