spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/db_hm_dress_recommender
    username: root
    password: rootpass
    jpa:
      hibernate.ddl-auto: validate
      generate-ddl: true
      show-sql: true
